# Generated by Django 6.0.3 on 2026-04-06 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Saree', 'Saree'), ('Punjabi', 'Punjabi'), ('Three-piece', 'Three-piece'), ('Shirt', 'Shirt')], default='Saree', max_length=50),
        ),
    ]
